[features]
seeds = false
skip-lint = false
[programs.localnet]
bitbuild = "DbnarSCFtEG44y2G99KmXxWgN6fwPoB48CUM8RHuecTQ"

[registry]
url = "http://localhost"

[provider]
cluster = "Localnet"
wallet = "home/asim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
