[features]
seeds = false
skip-lint = false
[programs.devnet]
bitbuild = "EhTgtig1RSswN44P1t3mj7qFGsZK9waWqxgSugBfHJCK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "private_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
